import { useEffect, useRef, useState } from 'react'
import { Apple, Bot, Check, ChevronLeft, Dumbbell, Footprints, Goal, History, LoaderCircle, LockKeyhole, MessageSquare, Plus, Scale, Send, Settings2, ShieldCheck, Sparkles, Trash2, UserRound, Waves, X } from 'lucide-react'
import { fitnessChatService } from '../services/fitnessChatService'
import { emptyFitnessPermissions, type AiConversation, type AiMessage, type FitnessAction, type FitnessPermission, type FitnessPermissions } from '../types/fitnessChat'

const permissionItems: Array<{ key: FitnessPermission; label: string; detail: string; icon: typeof UserRound }> = [
  { key:'profile', label:'Perfil', detail:'Nome, experiência e preferências de treino.', icon:UserRound }, { key:'objective', label:'Objetivo', detail:'Objetivo fitness informado no perfil.', icon:Goal },
  { key:'workouts', label:'Treinos', detail:'Fichas atuais e exercícios planejados.', icon:Dumbbell }, { key:'history', label:'Histórico', detail:'Sessões realizadas nos últimos dias.', icon:History },
  { key:'nutrition', label:'Alimentação', detail:'Totais de calorias e macronutrientes.', icon:Apple }, { key:'steps', label:'Passos', detail:'Passos e distância registrados.', icon:Footprints },
  { key:'water', label:'Água', detail:'Consumo e meta de hidratação.', icon:Waves }, { key:'weight', label:'Peso', detail:'Registros de evolução de peso.', icon:Scale },
  { key:'goals', label:'Metas', detail:'Metas ativas, progresso e prazos.', icon:Goal },
]
const suggestions = ['Como foi minha semana?', 'Quanto falta para bater minha proteína?', 'Estou sem tempo para treinar hoje', 'Faça um resumo do meu progresso']

export function FitnessChatPage({ userId }: { userId: string }) {
  const [conversations,setConversations] = useState<AiConversation[]>([]), [selected,setSelected] = useState<AiConversation|null>(null), [messages,setMessages] = useState<AiMessage[]>([])
  const [permissions,setPermissions] = useState<FitnessPermissions>({...emptyFitnessPermissions}), [permissionOpen,setPermissionOpen] = useState(false)
  const [input,setInput] = useState(''), [loading,setLoading] = useState(true), [sending,setSending] = useState(false), [error,setError] = useState(''), [sidebarOpen,setSidebarOpen] = useState(false)
  const [actionBusy,setActionBusy] = useState<string|null>(null)
  const messagesRef = useRef<HTMLDivElement>(null)

  useEffect(() => { let active=true; fitnessChatService.listConversations(userId).then((items)=>{if(!active)return;setConversations(items);if(items[0]){setSelected(items[0]);setPermissions(items[0].permissions)}else setPermissionOpen(true)}).catch((reason)=>active&&setError(messageOf(reason))).finally(()=>active&&setLoading(false)); return()=>{active=false} },[userId])
  useEffect(() => { if(!selected){setMessages([]);return}; let active=true; setLoading(true); fitnessChatService.listMessages(userId,selected.id).then((items)=>active&&setMessages(items)).catch((reason)=>active&&setError(messageOf(reason))).finally(()=>active&&setLoading(false)); return()=>{active=false} },[selected?.id,userId])
  useEffect(() => {
    const container = messagesRef.current
    if (container) container.scrollTo({ top: container.scrollHeight, behavior:'smooth' })
  },[messages,sending])

  async function chooseConversation(conversation:AiConversation){setSelected(conversation);setPermissions(conversation.permissions);setSidebarOpen(false);setError('')}
  function newConversation(){setSelected(null);setMessages([]);setPermissions({...emptyFitnessPermissions});setInput('');setPermissionOpen(true);setSidebarOpen(false)}
  async function savePermissions(){try{if(selected){await fitnessChatService.updatePermissions(userId,selected.id,permissions);const updated={...selected,permissions};setSelected(updated);setConversations((items)=>items.map((item)=>item.id===updated.id?updated:item))}setPermissionOpen(false)}catch(reason){setError(messageOf(reason))}}
  async function send(text=input){const content=text.trim();if(!content||sending)return;setSending(true);setError('');setInput('');const temp:AiMessage={id:`temp-${Date.now()}`,conversationId:selected?.id??'',role:'user',content,action:null,actionStatus:null,createdAt:new Date().toISOString()};setMessages((items)=>[...items,temp]);try{let conversation=selected;if(!conversation){conversation=await fitnessChatService.createConversation(userId,content.slice(0,46),permissions);setSelected(conversation);setConversations((items)=>[conversation!,...items])}const result=await fitnessChatService.send(conversation.id,content);setMessages((items)=>[...items.filter((item)=>item.id!==temp.id),result.userMessage,result.assistantMessage]);setConversations((items)=>items.map((item)=>item.id===conversation!.id?{...item,updatedAt:new Date().toISOString()}:item).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)))}catch(reason){setMessages((items)=>items.filter((item)=>item.id!==temp.id));setInput(content);setError(messageOf(reason))}finally{setSending(false)}}
  async function clearHistory(){if(!selected||!window.confirm('Limpar todas as mensagens desta conversa?'))return;try{await fitnessChatService.clearConversation(userId,selected.id);setMessages([])}catch(reason){setError(messageOf(reason))}}
  async function deleteConversation(){if(!selected||!window.confirm('Excluir esta conversa permanentemente?'))return;try{await fitnessChatService.deleteConversation(userId,selected.id);const remaining=conversations.filter((item)=>item.id!==selected.id);setConversations(remaining);setSelected(remaining[0]??null);if(remaining[0])setPermissions(remaining[0].permissions);else{setMessages([]);setPermissions({...emptyFitnessPermissions})}}catch(reason){setError(messageOf(reason))}}
  async function handleAction(messageId:string,action:FitnessAction,apply:boolean){if(actionBusy)return;setActionBusy(messageId);try{if(apply)await fitnessChatService.applyAction(userId,messageId,action);else await fitnessChatService.dismissAction(userId,messageId);setMessages((items)=>items.map((item)=>item.id===messageId?{...item,actionStatus:apply?'confirmed':'dismissed'}:item))}catch(reason){setError(messageOf(reason))}finally{setActionBusy(null)}}

  return <section className="fitness-chat-page">
    <aside className={`chat-history-panel ${sidebarOpen?'is-open':''}`}><div className="chat-history__top"><div><small>ASSISTENTE IA</small><strong>Conversas</strong></div><button className="chat-new-button" onClick={newConversation}><Plus size={16}/> Nova</button></div><div className="chat-conversation-list">{conversations.map((conversation)=><button key={conversation.id} className={selected?.id===conversation.id?'is-active':''} onClick={()=>void chooseConversation(conversation)}><MessageSquare size={15}/><span><strong>{conversation.title}</strong><small>{formatDate(conversation.updatedAt)}</small></span></button>)}{!conversations.length&&!loading&&<p>Nenhuma conversa salva.</p>}</div><div className="chat-history__privacy"><ShieldCheck size={16}/><p>Você decide quais dados cada conversa pode consultar.</p></div></aside>
    <div className="chat-main"><header className="chat-header"><button className="chat-mobile-back" onClick={()=>setSidebarOpen(true)} aria-label="Abrir conversas"><ChevronLeft size={18}/></button><span className="chat-ai-avatar"><Bot size={21}/><i/></span><div><strong>Assistente MOVELYA</strong><small><i/> IA disponível · respostas em português</small></div><button onClick={()=>setPermissionOpen(true)}><Settings2 size={16}/><span>Dados autorizados</span></button>{selected&&<button className="chat-icon-action" onClick={clearHistory} aria-label="Limpar histórico" title="Limpar histórico"><Trash2 size={16}/></button>}{selected&&<button className="chat-icon-action is-danger" onClick={deleteConversation} aria-label="Excluir conversa" title="Excluir conversa"><X size={17}/></button>}</header>
      <div ref={messagesRef} className="chat-messages" aria-live="polite">{loading?<div className="chat-loading"><LoaderCircle className="spin" size={24}/><p>Carregando conversa…</p></div>:!messages.length?<ChatWelcome onSuggestion={(value)=>void send(value)}/>:messages.map((message)=><ChatMessage key={message.id} message={message} busy={actionBusy===message.id} onAction={handleAction}/>)}{sending&&<div className="chat-bubble-row is-assistant"><span className="chat-message-avatar"><Bot size={16}/></span><div className="chat-bubble chat-typing"><i/><i/><i/></div></div>}{error&&<div className="chat-error" role="alert">{error}</div>}</div>
      <footer className="chat-composer"><div className="chat-safety-line"><LockKeyhole size={12}/> A IA não substitui profissionais e nunca aplica alterações sem sua confirmação.</div><div><textarea value={input} onChange={(event)=>setInput(event.target.value)} onKeyDown={(event)=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void send()}}} placeholder="Pergunte sobre sua rotina fitness…" maxLength={2000} rows={1}/><button onClick={()=>void send()} disabled={!input.trim()||sending} aria-label="Enviar mensagem"><Send size={18}/></button></div></footer>
    </div>
    {permissionOpen&&<PermissionDialog permissions={permissions} onChange={setPermissions} onClose={()=>setPermissionOpen(false)} onSave={()=>void savePermissions()}/>} 
  </section>
}

function ChatWelcome({onSuggestion}:{onSuggestion:(value:string)=>void}){return <div className="chat-welcome"><span><Sparkles size={27}/></span><small>SEU ASSISTENTE FITNESS</small><h1>Como posso ajudar hoje?</h1><p>Posso analisar apenas os dados que você autorizar e preparar sugestões para sua confirmação.</p><div>{suggestions.map((suggestion)=><button key={suggestion} onClick={()=>onSuggestion(suggestion)}>{suggestion}</button>)}</div><aside><ShieldCheck size={17}/><p>Não faço diagnósticos, prescrições médicas ou promessas de resultado. Em caso de dor ou lesão, priorizo sua segurança.</p></aside></div>}
function ChatMessage({message,busy,onAction}:{message:AiMessage;busy:boolean;onAction:(id:string,action:FitnessAction,apply:boolean)=>void}){return <div className={`chat-bubble-row ${message.role==='assistant'?'is-assistant':'is-user'}`}>{message.role==='assistant'&&<span className="chat-message-avatar"><Bot size={16}/></span>}<div><div className="chat-bubble">{message.content.split('\n').map((line,index)=><p key={index}>{line||<br/>}</p>)}</div>{message.action&&<ActionPreview action={message.action} status={message.actionStatus} busy={busy} onApply={()=>onAction(message.id,message.action!,true)} onDismiss={()=>onAction(message.id,message.action!,false)}/>}<small className="chat-message-time">{new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit'}).format(new Date(message.createdAt))}</small></div></div>}
function ActionPreview({action,status,busy,onApply,onDismiss}:{action:FitnessAction;status:AiMessage['actionStatus'];busy:boolean;onApply:()=>void;onDismiss:()=>void}){const summaryOnly=action.type==='weekly_summary';return <article className={`chat-action-card ${status&&status!=='pending'?`is-${status}`:''}`}><header><span>{summaryOnly?<Sparkles size={17}/>:<Settings2 size={17}/>}</span><div><small>PRÉVIA · NENHUMA ALTERAÇÃO APLICADA</small><strong>{action.title}</strong></div></header><p>{action.summary}</p><dl>{action.details.map((item)=><div key={`${item.label}-${item.value}`}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl>{status==='pending'?<footer><button onClick={onDismiss} disabled={busy}>Descartar</button><button onClick={onApply} disabled={busy}>{busy?<LoaderCircle className="spin" size={15}/>:<Check size={15}/>} {summaryOnly?'Entendi':'Confirmar alteração'}</button></footer>:<div className="chat-action-status">{status==='confirmed'?<><Check size={14}/> {summaryOnly?'Resumo visualizado':'Alteração confirmada'}</>:<>Sugestão descartada</>}</div>}</article>}
function PermissionDialog({permissions,onChange,onClose,onSave}:{permissions:FitnessPermissions;onChange:(value:FitnessPermissions)=>void;onClose:()=>void;onSave:()=>void}){const count=Object.values(permissions).filter(Boolean).length;return <div className="chat-permission-backdrop" onMouseDown={onClose}><section className="chat-permission-dialog" role="dialog" aria-modal="true" aria-labelledby="permissions-title" onMouseDown={(event)=>event.stopPropagation()}><header><span><ShieldCheck size={21}/></span><div><small>PRIVACIDADE</small><h2 id="permissions-title">Dados autorizados</h2></div><button onClick={onClose} aria-label="Fechar"><X size={18}/></button></header><p>Escolha o que a IA pode consultar nesta conversa. Você pode alterar isso a qualquer momento.</p><div className="permission-list">{permissionItems.map(({key,label,detail,icon:Icon})=><label key={key}><span><Icon size={16}/></span><div><strong>{label}</strong><small>{detail}</small></div><input type="checkbox" checked={permissions[key]} onChange={(event)=>onChange({...permissions,[key]:event.target.checked})}/></label>)}</div><footer><small>{count} de {permissionItems.length} categorias autorizadas</small><button onClick={onSave}><ShieldCheck size={15}/> Salvar permissões</button></footer></section></div>}
function formatDate(value:string){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(value))}
function messageOf(reason:unknown){return reason instanceof Error?reason.message:'Ocorreu um erro inesperado.'}
